### ISSUE TITLE
Add "location" feature 

### ISSUE THREAD

**Issue by kenanxiao0118** [Altimis/Scweet#10]
Hi,

Thank you so much for the wonderful work! Your code is really good to use. Would you add another the tweet's "location" feature to the final csv file? That would be a great help. Thanks again!

**Comment by Altimis** [comment]
Hi @kenanxiao0118, thank you, I'm glad that it has met your need. In fact, I think that the only way to retrieve tweets location is to "locate" to the user's profile (in case the ``from_account`` argument is not specified, which may take too long for thousands of tweets.

**Comment by kenanxiao0118** [comment]
Hi @Altimis ,

Yeah, I guess you're right. I guess it needs to go through the user_profile for the location info, and it may not be the real location that the tweet was made at. Thanks!
