### ISSUE TITLE
No contents in output file except the header row

### ISSUE THREAD

**Issue by ratobiajin** [Altimis/Scweet#101]
Hello! Thank you for the solution that worked fine for me in August 2021. Running on Python version 3.7.4 / IDLE version 3.7.4 on Win10. Please help. I'd like to acquire all tweets between start_date="2021-07-01", max_date="2022-01-03". Upon test run for a single date:

Scraping on headless mode.
looking for tweets between 2022-01-01 and 2022-01-02 ...
 path : https://twitter.com/search?q=(ラトビア%20OR%20ラトヴィア%20OR%20ラトヴィヤ%20OR%20ラトビヤ%20OR%20良都美野)%20until%3A2022-01-02%20since%3A2022-01-01%20&src=typed_query&f=live
scroll  1
scroll  2
scroll  3
scroll  4
scroll  5
scroll  6
scroll  7
scroll  8

The contents of the csv file in outputs folder is only this:
UserScreenName,UserName,Timestamp,Text,Embedded_text,Emojis,Comments,Likes,Retweets,Image link,Tweet URL

**Comment by Altimis** [comment]
Show me how did you set the scrape function please

**Comment by ratobiajin** [comment]
# -*- coding: utf-8 -*-
#coding: UTF-8

from Scweet.scweet import scrap
from Scweet.user import get_user_information, get_users_following, get_users_followers
data=scrap(words=['ラトビア','ラトヴィア','ラトヴィヤ','ラトビヤ','良都美野'],start_date="2022-01-01", max_date="2022-01-03",display_type="Latest",headless=True,interval=1)


This is the gather.pyw file contents, it looped and echoed a list scrolling instances for the date, but in the end the resulting csv file had just one line. In case if there is no viable solution, then I'd appreciate the scweeted tweets contents of the aforementioned half-year period.

**Comment by Altimis** [comment]
@ratobiajin it seems that you are using an old version of scweet. max_date and start_date are deprecated (replaced by since and until). Make sure that your are using Scweet version 1.8.

**Comment by ratobiajin** [comment]
Thank you very much for assistance. I reinstalled the version 1.8 and rewrote the function, and now it worked for the single date, so I will proceed on the whole aforementioned period. Hope it works. Please accept my gratitude and best wishes for development of this and your other projects!

**Comment by Altimis** [comment]
My pleasure !
