### ISSUE TITLE
Error when running scweet

### ISSUE THREAD

**Issue by ElGringo275** [Altimis/Scweet#11]
Hi, 

I have an error with selenium driver when I run the app. Any idea ? Thank's a lot for your help

> pip3 install -r requirements.txt
> pip3 install selenium
Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium) (1.24.1)

> python scweet.py --words "excellente//car" --to_account "tesla"  --max_date 2020-01-05 --start_date 2020-01-01 --limit 10 --interval 1 --navig chrome --display_type Latest --lang="en" --headless True
Traceback (most recent call last):
  File "scweet.py", line 5, in <module>
    from selenium.webdriver.common.keys import Keys
ImportError: No module named selenium.webdriver.common.keys

**Comment by Altimis** [comment]
@ElGringo275 In fact, this module is not needed anyway. Youcan delet the line ``from selenium.webdriver.common.keys import Keys``. I will push the changes right away.
