### ISSUE TITLE
max retrive 1000 tweets

### ISSUE THREAD

**Issue by okkymabruri** [Altimis/Scweet#13]
Hi @Altimis. I've tested Scweet several times in my machine (Linux OS), but I only get 1000 tweets. I think this is a limitation from Twitter. I don't know this issue in another OS.
Maybe it needs test in Windows/Mac and put  in the description that max retrieve Scweet is 1000 tweets due to Twitter limitation (I think)

my query
```python3 scweet.py --words "covid19//covid-19" --lang="id" --max_date 2020-03-19 --start_date 2020-03-18 --interval 1 --navig chrome --display_type Latest --headless True```

**Comment by Altimis** [comment]
Hi @okkymabruri, I tested it personnally and I could retrieve more than 30k tweets for only 20 days (from 2020-01-01 to 2020-01-20). What arguments did you use for scraping ? did you set ``--limit 1000`` ? did you set the ``--display_type Top`` ?

**Comment by Altimis** [comment]
Hi @okkymabruri , I just saw where is the problem. There is an arguement called ``--limit`` which is responsible for tweets to get for each ``--interval```. For example if you set ``start_date 2020-01-01`` and ``max_date 2020-05-01`` and you set  ``interval 30``, it means that you want to do a seach query for every 30 days interval. The default value of limit is 1000, so you can set as much limit as you want. 
![image](https://user-images.githubusercontent.com/48790841/103144049-0946e280-4723-11eb-800f-76d2e2ac6dae.png)

**Comment by okkymabruri** [comment]
Ah.. okay thanks @Altimis
