### ISSUE TITLE
Twitter timeline change (again), did this break Scweet?

### ISSUE THREAD

**Issue by biggestsonicfan** [Altimis/Scweet#138]
Twitter just felt the need to redesign itself again. I am wondering if this might be why I am returning `None` with everything.

Code:
```
from Scweet.scweet import scrape
from Scweet.user import get_user_information, get_users_following, get_users_followers

info = get_user_information("username", headless=False)
```

**Comment by amirreza1751** [comment]
Same issue here. 
get_user_information() method returns None even in the existing example of the repository.

**Comment by zwz20021023** [comment]
> 这里也存在同样的问题。> get_user_information()方法即使在存储库的现有示例中也返回无。Have you solved this question?

**Comment by biggestsonicfan** [comment]
Lol, closing due to Musky. RIP.
