### ISSUE TITLE
Cant get code to execute = Notebook / Pycharm

### ISSUE THREAD

**Issue by cunnial** [Altimis/Scweet#15]
Hi Altimis, thanks a stack for putting this together, I think I will get really good use of this if I can get it to work. I fear my lack of experience probably half the problem but when I copy your code into Jupyter Lab and change the run line (data = scrap(....)) to the following: 

data=scrap(max_date=2020-1-5,start_date=2020-1-1, to_account="tesla", interval=1,limit=10)

(Ive also tried using the format 2020-01-05)

I get the an error:

"usage: ipykernel_launcher.py [-h] [--words WORDS]
                             [--from_account FROM_ACCOUNT]
                             [--to_account TO_ACCOUNT] --max_date MAX_DATE
                             --start_date START_DATE [--interval INTERVAL]
                             [--navig NAVIG] [--lang LANG]
                             [--headless HEADLESS] [--limit LIMIT]
                             [--display_type DISPLAY_TYPE] [--resume RESUME]
                             [--proxy PROXY]
ipykernel_launcher.py: error: the following arguments are required: --max_date, --start_date
An exception has occurred, use %tb to see the full traceback."

I assume this means I cant run it out of Notebook?

Secondly the modules _**import datetimeKeys**_ and **_from selenium.common.exceptions import NoSuchElementExceptiondoesn't_** doesnt seem to exist? so when using pycharm it just goes grey. 

Finally if it's not too much to ask can you add a few lines to the readme.txt with some more examples as I used your exact example in the python terminal and count get it to execute? 

I see it working for others in the issues commentary so thanks for the code and appreciate the work given the loss of old school scrapers.

**Comment by Altimis** [comment]
Hi @cunnial , Thank you. You can check [this notebook](https://github.com/Altimis/Scweet/blob/master/Scweet/Example.ipynb). I'm  currently working on the library, but you can work with Scweet as a module.
