### ISSUE TITLE
Not collecting last batch of tweets

### ISSUE THREAD

**Issue by cunnial** [Altimis/Scweet#18]
Hi Altimis, been using your tool and working well. Although just noticed 2 issues: 

Issue 1. The last tweet collected was the reply to the chain of tweets from the user account I am scraping rather than the chain of tweets? some images for clarity:

Twitter user with last tweet: 
![Twitter User Account](https://user-images.githubusercontent.com/25256375/103356229-49ea8700-4aa8-11eb-80db-c467eb4bd732.jpg)

Output from Scraping:
![output](https://user-images.githubusercontent.com/25256375/103356252-57077600-4aa8-11eb-880b-19bc455c503b.jpg)

Actual tweet chain I was looking for:
![Screenshot 1](https://user-images.githubusercontent.com/25256375/103356270-638bce80-4aa8-11eb-8413-f2c0e6649eb4.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/25256375/103356275-65ee2880-4aa8-11eb-8a41-3387d666605a.jpg)

Issue 2: I also noticed there was a large chunk of tweets not scraped during mid November to beginning of December? Not sure why as there were tweets available.

![No scraping](https://user-images.githubusercontent.com/25256375/103356407-be252a80-4aa8-11eb-99e0-7f6566ea2973.jpg)

Here is the code input:
![Code](https://user-images.githubusercontent.com/25256375/103356515-f462aa00-4aa8-11eb-9ac8-1a30b197e5c0.jpg)

Any thoughts?

**Comment by Altimis** [comment]
@cunnial  Regarding issue 2, you should set the scraping with a headless chrome (headless = True). The problem is that when you set headless = False, you need to keep the chrome window on top, that's why I added the headless parameter. 
Regarding the first issue, by tweets, I meant all the tweets the user have done in the period between start_date and max_date, including replies. To eliminate these replies, you can do a simple filtring in the 'tweets' columns where you'll need to remove all the text that begins with 'replying to'.

**Comment by cunnial** [comment]
> @cunnial Regarding issue 2, you must start scraping with a headless chrome (headless = True). The problem is that when you set headless = False, you need to keep the chrome window on top, that's why I added the headless parameter.
> Regarding the first issue, by tweets, I meant all the tweets the user have done in the period between start_date and max_date, including replies. To eliminate these replies, you can do a simple filtring in the 'tweets' columns where you'll need to remove all the text that begins with 'replying to'.

Hi Altimis, regarding issue 1, that's the thing, all the tweets in those screenshots from Jam_Croissant labelled "1/x, 2/x to 6/6" weren't collected, only the last tweet in that chain which was a reply to someone else? One for next week - Happy new year and I hope 2021 brings you many success with your work!

**Comment by Altimis** [comment]
@cunnial Thank you so much for your wishes. I think that the the scripts missed those tweets for the same reason as issue 2. Can you call the function one again, but this time with a headless chrome window (headless = True) ?

**Comment by cunnial** [comment]
HNY Altimis! 

This has worked great. I also changed the tweet type to Latest and getting all the right information now.

Great work! Ticket closed from my end!

**Comment by Altimis** [comment]
HNY @cunnial,

Happy for you ! In fact, I forgot about the ``Display_type`` parameter.
