### ISSUE TITLE
Scrape all tweets from a specific account

### ISSUE THREAD

**Issue by OmniSec001** [Altimis/Scweet#2]
Can you make it so that the word is not an actual requirement if you want to scrape tweets coming from a specific account? Would be awesome for that to not be mandatory rather an extra feature.

**Comment by Altimis** [comment]
Actually that's a good point. Thank you I will do it right now.

**Comment by Altimis** [comment]
@OmniSec001  Done.

**Comment by Frank-LIU-520** [comment]
> @OmniSec001 Done.

Still don't get how to scrape all the information from one account. Could you two please show us an example on the Scrape function?
