### ISSUE TITLE
Not collecting some fields in the CSV

### ISSUE THREAD

**Issue by manuc95** [Altimis/Scweet#22]
Hi, thank you very much for this exceptional code!!

I just found a little problem, can you help me to understand if I'm missing something?

In the output CSV, I found all the information except for the followings:
- 'Emojis' : emojis existing in tweet
- 'Comments' : number of comments
- 'Likes' : number of likes
- 'Retweets' : number of retweets

**Comment by Altimis** [comment]
Hi @manuc95. Thank you !
I think the reason behind this is that the tweets that you scraped have neither likes nor comments and retweets, maybe they also have no emojis. I just tried it my self and it gave me these results :

![image](https://user-images.githubusercontent.com/48790841/103559387-56128200-4eb6-11eb-9243-03ba801e214e.png)

I recommande you to scrape data for a large period of time to confirm the assumption.

**Comment by manuc95** [comment]
> Hi @manuc95. Thank you !
> I think the reason behind this is that the tweets that you scraped have neither likes nor comments and retweets, maybe they also have no emojis. I just tried it my self and it gave me these results :
> 
> ![image](https://user-images.githubusercontent.com/48790841/103559387-56128200-4eb6-11eb-9243-03ba801e214e.png)
> 
> I recommande you to scrape data for a large period of time to confirm the assumption.

oops I'm sorry it's right.. and it's working correctly!
I just found something like 20 tweets without any likes or comments, bad luck ahah

Just a small thing for your code: the default value for Lang is "en" instead of None. Maybe it could be not clear for somebody

Moreover, I'm making a code to scrap both tweets and user information of the user that made the tweet. Just let me know if it could be interesting for you (maybe to add an example, I think that it could be interesting for somebody)

Thank you again!
Manuel

**Comment by Altimis** [comment]
@manuc95 
Yes it's true, I just changed the default value of ``lang`` as ``None``. 
Your code sounds interesting. In fact, Scweet enable you to scrape tweets and the corresponding information, but it can only scrape information of a specific user (not every user of each tweet scraped as you said). So your solution could be useful in this code, I would be appreciated for it.

**Comment by manuc95** [comment]
> @manuc95
> Yes it's true, I just changed the default value of `lang` as `None`.
> Your code sounds interesting. In fact, Scweet enable you to scrape tweets and the corresponding information, but it can only scrape information of a specific user (not every user of each tweet scraped as you said). So your solution could be useful in this code, I would be appreciated for it.

Hi Altimis, sorry for the delay but I had other stuff to do before finished this code. I hope that the following could be useful for someone!

At the moment, it is working only for simple researches (eg. Trump Election) and not for particular ones (eg. Trump//Election)
But the logic of the code is working, it is just a matter of correctly read/rewrite the name of the CSV made in the first step

I know that there are probably a lot of fastest ways to do that, but I'm just an entry-level on Python, sorry! 

```
from scweet import scrap
from user import get_user_information, get_following, get_followers
import pandas as pd
from datetime import datetime

startdate="2020-01-01"
enddate="2020-12-31"
account=None #None to don't filter by account
hash_tag=None #None to don't search by hashtag
textsearch="Lemanik Funds" #None to don't search by words
lan=None #en or it to filter by language

d1 = datetime.strptime(startdate, "%Y-%m-%d")
d2 = datetime.strptime(enddate, "%Y-%m-%d")
interv=abs((d2 - d1).days)
#This is to use the entire time interval in the research. You can reduce it if you prefer!

scrap(start_date=startdate,max_date=enddate,words=textsearch,from_account=account,interval=interv,navig="chrome",headless=True,display_type="Top",hashtag=hash_tag,lang=lan)

#Now, we have scraped the Tweets. For each Tweet we'll go to scrape info from the username!

if textsearch is not None:
    txtname=textsearch
elif hash_tag is not None:
    txtname=hash_tag
elif account is not None:
    txtname=account
else:
    txtname=""
    print("Insert at least one filter")

namecsv = r'outputs\\' + txtname + "_" + startdate + "_" + enddate + ".csv"

df=pd.read_csv(namecsv, sep=',', dtype=object)

#ADD NEW COLUMS FOR USER INFO
df["following"] = None
df["followers"] = None
df["join_date"] = None
df["location"] = None
df["website"] = None
df["description"] = None
df = df.copy()

for jj in range (0, len(df)):
    usern=df.iloc[jj]["UserName"][1:]
    following, followers, join_date, location, website, description = get_user_information(usern)
    df.iloc[jj]["following"] = following
    df.iloc[jj]["followers"] = followers
    df.iloc[jj]["join_date"] = join_date
    df.iloc[jj]["location"] = location
    df.iloc[jj]["website"] = website
    df.iloc[jj]["description"] = description

df.to_csv(namecsv, mode="w", index=False, header=True)
print("\ndone!")
```
