### ISSUE TITLE
Importing the module

### ISSUE THREAD

**Issue by reachyou91** [Altimis/Scweet#23]
Hi, Thank you for your effort.

I am a beginner trying to use your module in Google Colab with the example you provided but it failed. I installed your module either by git cloning or by pip command. It seems the package installed with the name of 'Scweet' (capital letter) but still I cannot import the scrap. Could anyone please let me know how to successfully import it? Thanks in advance. 

![image](https://user-images.githubusercontent.com/25308509/103720071-829eca80-4f98-11eb-8b69-f48c34c5bc28.png)

![image](https://user-images.githubusercontent.com/25308509/103719985-4b301e00-4f98-11eb-9e75-73b4a1bb930d.png)

**Comment by Kittyuzu1207** [comment]
I encountered the same, and I used "from Scweet.scweet import scrap" to solve it. After that, there may be other errors about utils.py and const.py, you can enter these files and modify the code "import utils" by "import Scweet.utils" etc. and it can work well.

**Comment by Altimis** [comment]
I recommande you clone the project and use the sample notebook. There is just a beta version of the library and actually there are a lot of problems with it.

**Comment by reachyou91** [comment]
> I encountered the same, and I used "from Scweet.scweet import scrap" to solve it. After that, there may be other errors about utils.py and const.py, you can enter these files and modify the code "import utils" by "import Scweet.utils" etc. and it can work well.

Thank you. However, after I import utils and const as you mentioned, I encounter "SCWEET_USERNAME returned None but this is not allowed!"

**Comment by reachyou91** [comment]
> I recommande you clone the project and use the sample notebook. There is just a beta version of the library and actually there are a lot of problems with it.

Thank you for reply. I cloned the project on the notebook but it generates the same error I mentioned above.

**Comment by Altimis** [comment]
> > I recommande you clone the project and use the sample notebook. There is just a beta version of the library and actually there are a lot of problems with it.
> 
> Thank you for reply. I cloned the project on the notebook but it generates the same error I mentioned above.

After cloning, you need to locate to the repository to be able to use the scweet module. When you cloned it, you tried to call directly the scweet module, but it is not in your path since there still are a lot of issues in the library, so you need to locate manually to the directory of the project and call the above functions (I recommend you open the sample.ipynb file and use it as your notebook).

**Comment by reachyou91** [comment]
> > > I recommande you clone the project and use the sample notebook. There is just a beta version of the library and actually there are a lot of problems with it.
> > 
> > 
> > Thank you for reply. I cloned the project on the notebook but it generates the same error I mentioned above.
> 
> After cloning, you need to locate to the repository to be able to use the scweet module. When you cloned it, you tried to call directly the scweet module, but it is not in your path since there still are a lot of issues in the library, so you need to locate manually to the directory of the project and call the above functions (I recommend you open the sample.ipynb file and use it as your notebook).

I see. Thank you for your kind explanation!
