### ISSUE TITLE
Found 0 following when crawling following information

### ISSUE THREAD

**Issue by Kittyuzu1207** [Altimis/Scweet#24]
Hi, thanks for your excellent tool! I met a problem and want to know how to solve it. When I crawl following list of users, after I got info of 5 accounts, I only get "Found 0 following" for remaining users, whose following lists are actually not empty. I set the "wait" param as 3, and I even wait for 20s after crawling several users. The username and password can be normally used in the webpage of Twitter. I wonder how I can solve this problem~ 
Thank you so much!
![image](https://user-images.githubusercontent.com/62416241/103762009-90b12180-5052-11eb-89b4-c02366b96266.png)

**Comment by Kittyuzu1207** [comment]
Also, it sometimes mention"error with: xxx", still can get nothing.

**Comment by Altimis** [comment]
Hi, thank you. 
Actually I've never tried to scrape the followers of that much users before. I think the problem here i duo to the account you are using. I think Twitter have banned your account and you cant get access to user followers/following anymore. I'm working on a better method to scrape these kind of information (the accurate wait parameter to use ... ). 

I guess one solution might be to create a new function that scrapes followers for many users. The main reason why Twitter may ban your account is logging in several times.

**Comment by Kittyuzu1207** [comment]
> Hi, thank you.
> Actually I've never tried to scrape the followers of that much users before. I think the problem here i duo to the account you are using. I think Twitter have banned your account and you cant get access to user followers/following anymore. I'm working on a better method to scrape these kind of information (the accurate wait parameter to use ... ).
> 
> I guess one solution might be to create a new function that scrapes followers for many users. The main reason why Twitter may ban your account is logging in several times.

Hi, thank you for reply. When logging in the webpage of Twitter, the account works normally. I may register another account and retry it.

**Comment by Altimis** [comment]
Hi @Kittyuzu1207 , I think i solver this issue by updating the ``get_followers`` and ``get_following`` function to ``get_users_followers`` and ``get_users_following``. You can check the example notebook.

**Comment by Kittyuzu1207** [comment]
> Hi @Kittyuzu1207 , I think i solved this issue by updating the `get_followers` and `get_following` functions to `get_users_followers` and `get_users_following` that can crawl following and followers for many users without the need to log in each time. You can check the example notebook.

Hi, thank you for this update! I had the same idea so I have already modified the source code so that I only need to log in once and get following of many users. It's nice of you to make this public. : )
