### ISSUE TITLE
.env credentials format

### ISSUE THREAD

**Issue by guilherme-sal** [Altimis/Scweet#29]
Hi Altimis, thank you for your effort!

The script is running smooth in my machine. The only exception is the get_users_following and get_users_followers functions.

I create a .env file in the main directory, inserted my username and password but still couldn't return user's followers or following. 

I am not sure which format for the credentials I should use in the .env file. Can you help me?

Thanks!

**Comment by Altimis** [comment]
Hi, thank you @guilherme-sal.

here is an example
![image](https://user-images.githubusercontent.com/48790841/104755084-4c143d00-575a-11eb-80e3-f44ffdb645f5.png)

**Comment by guilherme-sal** [comment]
Thanks! I did that and restarted kernel. Now everything is working fine!

**Comment by thezakman** [comment]
Weird, i tried to login in my bot account and didn't work. 
Any ideas why?
