### ISSUE TITLE
didn't get all of the tweets

### ISSUE THREAD

**Issue by PanXinglin** [Altimis/Scweet#30]
Thank you so much for this repository！But I met up with a problem.
I try to run  `scrap(start_date="2020-01-11", max_date="2020-01-16", words = "tesla",interval=1, headless=True, display_type="Top", hashtag=None)` 
you know, there are thounds of tweets about tesla each day, but I got only 360+ tweets from "2020-01-11" to "2020-01-16".
Could u help me please? Thanks a lot!

**Comment by PanXinglin** [comment]
I tried again without headless mode. I found :
![image](https://user-images.githubusercontent.com/53027709/104798720-f85e2e00-5803-11eb-9e11-0abfaa16e2f2.png)
this situation has ever taken place when I try to directly get this page using selenium, because javascript doesn`t work

**Comment by Altimis** [comment]
@PanXinglin  Yes it's normal. You set the ``display_type`` parameter as Top and not Latest. Top shows only top tweets, but latest shows all the tweets starting from the latest ones.
