### ISSUE TITLE
Username case sensitive

### ISSUE THREAD

**Issue by DiweenHawezy** [Altimis/Scweet#33]
Is it possible to remove case sensitivity in the user search ? I tried using .casefold() in user.py but didn't get very far. 

For example, for the username 'user'. this won't work if the twitter handle is @User. I have a large database of usernames but it is all in lowercase.

Thank you for your time.

**Comment by Altimis** [comment]
Hi @DiweenHawezy,
Please check the changes, the issue is solved.

**Comment by DiweenHawezy** [comment]
> 
> 
> Hi @DiweenHawezy,
> Please check the changes, the issue is solved.

Thanks !
