### ISSUE TITLE
Join Date and Birthday Mixed up

### ISSUE THREAD

**Issue by DiweenHawezy** [Altimis/Scweet#34]
Hi, 

if the username has a birthday presented on the profile, this is scraped instead of the join date.

Regards,

**Comment by Altimis** [comment]
Can you please provide me with a username example that has birthday presented on their profile ?

**Comment by DiweenHawezy** [comment]
> 
> 
> Can you please provide me with a username example that has birthday presented on their profile ?

Here is one example:

"geceeekusuu"

**Comment by DiweenHawezy** [comment]
For this account, the join date is not picked up:

@HalimSaskin

**Comment by Altimis** [comment]
@DiweenHawezy  thank you for making these tests, I'll make some changes soon.

**Comment by Altimis** [comment]
@DiweenHawezy  check the changes.

**Comment by DiweenHawezy** [comment]
Thank you.
