### ISSUE TITLE
What should I do if I just want to catch the information according to 'keyword' without 'from_account'

### ISSUE THREAD

**Issue by XXXholics** [Altimis/Scweet#39]
I am looking for some hot spot content on Twitter, and I want to analyze how one hot spot grows. But it seems that I can only search information within the 'from_account' I give. 

I really want a function to do global search without the limitation of 'from_account'. Could you help me?

**Comment by Altimis** [comment]
You can use ``words`` parameter to search for specific words (its type is ``list``). Is this what you need ?

**Comment by XXXholics** [comment]
> You can use `words` argument to search for specific words (its type is `list`). Is this what you need ?

Thank you for your kind reply!

**Comment by XXXholics** [comment]
> You can use `words` argument to search for specific words (its type is `list`). Is this what you need ?

However, I met another problem.
I didn't change your code, but I can't import this module into the Jupyter, I mean I can't use the Example.ipynb provided in the project, but I can successfully use cmd to run ">python scweet.py --words "tesla" --start_date "2020-01-11" --max_date "2020-01-16" --interval 1 --headless True --display_type "Top""

If I use Jupyter, it will say  SCWEET_USERNAME returned None but this is not allowed!
![image](https://user-images.githubusercontent.com/52038813/105583448-1ced7380-5dcb-11eb-9a7b-8476e5fe345f.png)

**Comment by Altimis** [comment]
@XXXholics  check the changes that I made.

**Comment by XXXholics** [comment]
> @XXXholics check the changes that I made.

Thank you so much! I figured out all these questions! Thanks for your contribution!
