### ISSUE TITLE
Twitter search not work via scweet with selenium

### ISSUE THREAD

**Issue by LangInteger** [Altimis/Scweet#45]
My Code:
```python
from scweet import scrap
from user import get_user_information, get_users_following, get_users_followers

data = scrap(words = 'world', start_date="2020-02-07", max_date="2020-02-09",interval=1, limit=10,
      headless=False, proxy="socks5://127.0.0.1:7891")
```

Run the code in non-headless mode, I can see that there is an error got when searching:
![image](https://user-images.githubusercontent.com/17768055/107309052-b18eeb80-6ac4-11eb-89f1-4cc3d8fd7344.png)

But if I run the query from https://twitter.com/search manually, everything works fine:

![image](https://user-images.githubusercontent.com/17768055/107309101-c79cac00-6ac4-11eb-910e-e795c5db38fd.png)

**Comment by Altimis** [comment]
I guess the problem comes from the proxy you are using

**Comment by LangInteger** [comment]
Make sense, but hard to debug. thx

**Comment by Altimis** [comment]
@LangInteger  did you try other proxies ? If you are from China, I know many people who used scweet even without proxy.. So I dont know honestly how we could resolve this issue

**Comment by LangInteger** [comment]
Yeah, from mainland China.

Without proxy set, I will get an error when accessing twitter:

![image](https://user-images.githubusercontent.com/17768055/107310010-7db4c580-6ac6-11eb-8c24-f25cc2cc8cb2.png)

When with proxy, at least twitter is opened, I'll try other methods and feedback if find something new.

**Comment by LangInteger** [comment]
![image](https://user-images.githubusercontent.com/17768055/107310693-e05a9100-6ac7-11eb-98f1-9e5e2542ad41.png)

It's weird that got http code 401.

**Comment by LangInteger** [comment]
![image](https://user-images.githubusercontent.com/17768055/107310848-30395800-6ac8-11eb-905b-6b6a0afbd40e.png)

If I access twitter.com from Chrome window opened by selenium, I'm forced to log in and can access twitter after that. So maybe twitter find some potential risk in my access and some security strategy makes it do so.

**Comment by LangInteger** [comment]
Finally, I have to set my twitter username & password in the .env file and everything works fine.

I made a mistake in the earlier statement that I can access twitter.com manually is because I have login twitter several days before.
