### ISSUE TITLE
Argument to exlude embeded/reply text

### ISSUE THREAD

**Issue by leddy231** [Altimis/Scweet#48]
https://github.com/Altimis/Scweet/blob/87138a4b3dd3a67c7de024b1051d3027832f6013/Scweet/utils.py#L53

Currently, this line concatinates the text with the embeded text in the tweet. This happens for replys, wich could be usefull, but also for all embeded text, from linked websites/videos/etc

We are using this tool to scrape swedish data, and I found it usefull to change this line to not inlcude the embeded texts, since they are often in english.
I would suggest a argument to scweet to enable/disable the reply/embeded text
Or maybe add the reply text in a separate column in the CSV file? for easier processing

Thank you for this tool!

**Comment by Altimis** [comment]
Hey, sorry for the late response. You are right, I will separate them and add an embedded column to the csv file.
