### ISSUE TITLE
"from_account=" function returning tweets posted by other accounts

### ISSUE THREAD

**Issue by maivierzhent** [Altimis/Scweet#50]
Thanks for developing this very useful scraper! 
I used the from_account function but were still receiving tweets posted by other accounts that are replying to them. How to fix this?
Also, I am trying to scrape the tweets posted by specific accounts, not their responses to others. Is there a way to filter them out?

Thank you for your help!

**Comment by Altimis** [comment]
Hi @maivierzhent, thank you. Yes you can set the parameter ``filter_replies=True`` to filter the replies.

**Comment by maivierzhent** [comment]
I did, but the returned data still included the replies. Could you please help me see how to fix the following code? Thank you!

data = scrap(from_account="@SouthwestAir",start_date="2020-4-1", max_date="2020-4-3", interval=1, lang="en",
      headless=True, display_type="Top", save_images=False, resume=False, filter_replies=True)

**Comment by Altimis** [comment]
There was a typo error in the utils file. Check if it works now please.

**Comment by maivierzhent** [comment]
working now! Thank you so much!!
