### ISSUE TITLE
Packaging Scweet as a Conda or Pip library

### ISSUE THREAD

**Issue by BrandonKMLee** [Altimis/Scweet#53]
Since Twint already has that covered, why not allow Scweet to be accessible as well?
Take a look at https://pypi.org/
Observing https://github.com/Altimis/Scweet/blob/master/setup.py exists, the **documentation could be changed**

**Comment by BrandonKMLee** [comment]
- https://www.freecodecamp.org/news/build-your-first-python-package/
- https://www.programiz.com/python-programming/package
- https://www.pythoncentral.io/how-to-create-a-python-package/
- https://towardsdatascience.com/how-to-open-source-your-first-python-package-e717444e1da0

**Comment by Altimis** [comment]
Done. Thank you Brandon.
