### ISSUE TITLE
Less number of tweets for more historic data.

### ISSUE THREAD

**Issue by abhi5154** [Altimis/Scweet#61]
The last 7-8 days of a topic has nearly four times the number of tweets compared to more distant history.
Is there a reason for that?

**Comment by Altimis** [comment]
Did you set display_type  as Top or Latest ?

**Comment by abhi5154** [comment]
display_type is Top

**Comment by princeofstacking** [comment]
@abhi5154  are the tweets being stored in the data for you?

**Comment by Altimis** [comment]
> display_type is Top. should i use latest?

set it as Latest and it will work for you. Top means that you are scraping only top tweets in terms of likes and retweets.

**Comment by Altimis** [comment]
> @abhi5154 are the tweets being stored in the data for you?

I know what you are talking abou, I forgot to set a path variable for saving the csv file in the case of library. You can clone the repo and scrap using the notebook and you will find the file in output directory. I will update the library
