### ISSUE TITLE
not scrapping anything!

### ISSUE THREAD

**Issue by princeofstacking** [Altimis/Scweet#62]
it just scrolls and is unable to find anything using both keywords and hashtags. No is extracted from twitter.

**Comment by Altimis** [comment]
Copy the link of the search and past it in your browser to see if it works.

**Comment by monstertony** [comment]
You need to set headless and proximity both to True

**Comment by Altimis** [comment]
> You need to set headless and proximity both to True

Proximity has nothing to do with that. I guess he needs to set a proxy... Anyways I need to see if he can access twitter manually with the same parameters (same dates, keywords...)

**Comment by monstertony** [comment]
I know, I tried copy the link. It doesn't work for me, the page says has no results. So I set these two to false, it worked. Just find the easiest way to fix, not the right way........

**Comment by Altimis** [comment]
Ah then in your case, there were no tweets with such keywords at your proximity (your country or city). This is true if you set proximty to false.

**Comment by monstertony** [comment]
> Ah then in your case, there were no tweets with such keywords at your proximity (your country or city). This is true if you set proximty to false.

Ah, that's why. Thanks anyway! Very nice project!
