### ISSUE TITLE
Limit followers/following scrap results

### ISSUE THREAD

**Issue by icpgithub** [Altimis/Scweet#71]
Hi,

Is there a way to limit the followers scraping? For instance, I will like to only scrap the newest X followers from users using this function:

followers = get_users_followers(users=users, verbose=0, headless = False, wait=1)

Is this something that can be implemented? Or is there and I don't know how to use it? 🔥

**Comment by Altimis** [comment]
Done

**Comment by icpgithub** [comment]
Thanks!
