### ISSUE TITLE
How can I limit the number of followers and followings to be fetched from get_users_following and get_users_followers?Because I only need 1000 followers or followings .

### ISSUE THREAD

**Issue by purnima110895** [Altimis/Scweet#77]

**Comment by purnima110895** [comment]
@Altimis Please reply .

**Comment by Altimis** [comment]
I added this feature yesterday to the repository. I've not updated the library yet. Clone the code and you can use it by setting the ``limit`` parameter in the get_users_following and get_users_followers functions.

**Comment by Altimis** [comment]
@purnima110895  Sorry I've just pushed the changes.

**Comment by purnima110895** [comment]
Getting this error @Altimis ,

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-b7d5ccde9aa4> in <module>
----> 1 followers = get_users_followers(users=users, env=env_path, verbose=0, headless=True, wait=2, limit=300)

TypeError: get_users_followers() got an unexpected keyword argument 'limit'

I have scweet 1.1 version??

**Comment by Altimis** [comment]
Yes that's what I said. I did not update the version of the library yet, I need to do some other changes to do so. But the limit parameter has been added to the repo in github. So you need to clone it and work with it instead of the library. 

``git clone https://github.com/Altimis/Scweet.git``  

and you can use the Example.py as a guide.

**Comment by Altimis** [comment]
If it doesn't work for you let me now to create a new version of the library.

**Comment by Altimis** [comment]
You can try using the new version now : 1.2

**Comment by purnima110895** [comment]
Cool!!Thank you so much @Altimis . It's working good.
