### ISSUE TITLE
getting timeout exception in the function following = get_users_following(users=users,env=env_path, verbose=0, headless = True,wait=5, limit=10)

### ISSUE THREAD

**Issue by purnima110895** [Altimis/Scweet#78]
selenium.common.exceptions.TimeoutException: Message:
TimeoutException: Message: timeout: Timed out receiving message from renderer: 97.807

![scweet_timeout_error] Refer the error image below -
https://user-images.githubusercontent.com/88534418/128830857-51dba4e4-717d-4214-a303-3eb0792b1630.png

Why so? Any solution to avoid this @Altimis .

**Comment by purnima110895** [comment]
Resolved!

**Comment by qiangjiaodeyugang** [comment]
How did you solve it?
