### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome': 'google-chrome'

### ISSUE THREAD

**Issue by purnima110895** [Altimis/Scweet#79]
I am running only the Example.ipynb , and getting this error on linux platform, how can I fix this, because I need only following/followers functions of scweet?
Please reply @Altimis

**Comment by Altimis** [comment]
Do you have google-chrome installed in your system ?

**Comment by purnima110895** [comment]
actually, it was not installed, let me check once after installing.

**Comment by purnima110895** [comment]
> Do you have google-chrome installed in your system ?

google-chrome --version
Google Chrome 92.0.4515.131

selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by Altimis** [comment]
It's a permission issue i guess ...

**Comment by Altimis** [comment]
I have a solution that may work for you, I'll update the lib later. 
Go to the source code of the scweet library in your system (look for it in site_packages folder where all packages are being stored). Go to utils.py and look for init_driver function. Then add this line ``options.add_argument("--no-sandbox")`` before this line ``driver = webdriver.Chrome(options=options, executable_path=chromedriver_path)``

**Comment by purnima110895** [comment]
But I am not running the scweet file, I am just running the example.py file, and using only the following and follower functions.

**Comment by Altimis** [comment]
It's the same thing. All the modules in the scweet library uses chrome-driver so you need to get your chrome working.

**Comment by purnima110895** [comment]
okay,I will try your solution. Thankyou.
Any solutions that can be updated in example.py?

**Comment by Altimis** [comment]
Not really, the problem exists in the core of the process. The first step is to open chrome (in headless mode). In your case chrome doesnt open duo to permission issues. If you set this option before opening chrome with selenium, you might get it work. Keep me updated so i can add this option for linux users

**Comment by Altimis** [comment]
See [this issue](https://github.com/SeleniumHQ/selenium/issues/4961#issuecomment-365251536)

**Comment by purnima110895** [comment]
okay, I will update if I face any other issue after the above solutions doesn't work. Thankyou.

**Comment by purnima110895** [comment]
> I have a solution that may work for you, I'll update the lib later.
> Go to the source code of the scweet library in your system (look for it in site_packages folder where all packages are being stored). Go to utils.py and look for init_driver function. Then add this line `options.add_argument("--no-sandbox")` before this line `driver = webdriver.Chrome(options=options, executable_path=chromedriver_path)`

It resolved the issue, Thankyou @Altimis .

**Comment by Altimis** [comment]
Great ! I'll add this option later. Although I read that this option is not recommanded idk why exactly.
