### ISSUE TITLE
It doesn't scrap anything.

### ISSUE THREAD

**Issue by nodays0502** [Altimis/Scweet#87]
Hello
yesterday it works good 
but, today this code It doesn't scrap anything.....

data = scrape(hashtag="dog", since="2021-09-09", until=None, from_account = None, interval=1, 
              headless=True, display_type="Top", save_images=False, 
              resume=False, filter_replies=True, proximity=True)

data = scrape(hashtag="dog", since="2021-09-09", until=None, from_account = None, interval=1, 
              headless=False, display_type="Top", save_images=False, 
              resume=False, filter_replies=True, proximity=True)

data = scrape(words=['dog'], since="2021-09-08", until="2021-09-09", from_account = None, interval=1, 
              headless=True, display_type="Top", save_images=False, 
              resume=False, filter_replies=False, proximity=False)

All didn't work

help me plz

```
looking for tweets between 2021-08-05 and 2021-08-07 ...
 path : https://twitter.com/search?q=(dog)%20until%3A2021-08-07%20since%3A2021-08-05%20%20-filter%3Areplies&src=typed_query&f=live
scroll  1
scroll  2
scroll  3
scroll  4
scroll  5
scroll  6
scroll  7
scroll  8
scroll  9
```

**Comment by cihan-github** [comment]
I am having the same problem. I couldn't find any solution no matter what I did. 
Can you help us @Altimis ?

**Comment by cihan-github** [comment]
Did you find any solution? @nodays0502

**Comment by Altimis** [comment]
Yes you are right. Give me some time to check it

**Comment by cihan-github** [comment]
Thank @Altimis very much for your interest. I will be waiting for a message from you.

**Comment by cihan-github** [comment]
@Altimis, did you find any solution? Because I'm trying to run a project for next week.

**Comment by nodays0502** [comment]
sry... i don't have no idea ... @cihan-github

**Comment by Altimis** [comment]
@cihan-github  @nodays0502  check the new version (1.6) and tell me if it works for you. Twitter updated the xpath of tweets so I had to change it.

**Comment by Georgebillion** [comment]
New Version 1.6 Is Solved This Problem. It's  Worked!!! @Altimis 

Here's some codes:
looking for tweets between 2021-05-25 and 2021-06-02 ...
 path : https://twitter.com/search?q=(PetraArt%20OR%20ペト絵%20OR%20GalleryOfRoses%20OR%20Artsuki%20OR%20絵リーラ%20OR%20pendorART%20OR%20Finanart%20OR%20PomuPaint)%20until%3A2021-06-02%20since%3A2021-05-25%20&src=typed_query&f=image
Tweet made at: 2021-05-28T01:05:36.000Z is found.
Tweet made at: 2021-05-27T21:08:12.000Z is found.
Tweet made at: 2021-05-30T22:50:48.000Z is found.
Tweet made at: 2021-05-31T00:52:42.000Z is found.
scroll  1
Tweet made at: 2021-05-26T01:22:58.000Z is found.
Tweet made at: 2021-05-31T01:49:19.000Z is found.
Tweet made at: 2021-05-30T02:00:38.000Z is found.
Tweet made at: 2021-05-29T05:40:58.000Z is found.

**Comment by Altimis** [comment]
@Georgebillion  Perfect. Thank you.
