### ISSUE TITLE
timeout exception when trying to get user following

### ISSUE THREAD

**Issue by Evan-Ning** [Altimis/Scweet#98]
Hi, thanks for the package. I keep getting a timeout exception when I try to use the get_users_following() function or the get_users_followers() function. All other functions work fine. Is there any way I can fix this problem? 

My env file looks like this: SCWEET_USERNAME=......,SCWEET_PASSWORD=......

And I keep getting the following error:
TimeoutException                          Traceback (most recent call last)
<ipython-input-402-147d482c5de4> in <module>
----> 1 following = get_users_followers(users=['SenSanders'],
      2                                 env=env_path, verbose=0, headless = False,
      3                                 wait=6,file_path=None)

/opt/anaconda3/lib/python3.8/site-packages/Scweet/user.py in get_users_followers(users, env, verbose, headless, wait, limit, file_path)
     98 def get_users_followers(users, env, verbose=1, headless=True, wait=2, limit=float('inf'), file_path=None):
     99 
--> 100     followers = utils.get_users_follow(users, headless, env, "followers", verbose, wait=wait, limit=limit)
    101 
    102     if file_path == None:

/opt/anaconda3/lib/python3.8/site-packages/Scweet/utils.py in get_users_follow(users, headless, env, follow, verbose, wait, limit)
    271     follows_users = {}
    272 
--> 273     for user in users:
    274         # if the login fails, find the new log in button and log in again.
    275         if check_exists_by_link_text("Log in", driver):

/opt/anaconda3/lib/python3.8/site-packages/Scweet/utils.py in log_in(driver, env, timeout)
    206     username_el.send_keys(username)
    207     password_el.send_keys(password)
--> 208     password_el.send_keys(Keys.RETURN)
    209 
    210 

/opt/anaconda3/lib/python3.8/site-packages/selenium/webdriver/support/wait.py in until(self, method, message)
     87             if time.time() > end_time:
     88                 break
---> 89         raise TimeoutException(message, screen, stacktrace)
     90 
     91     def until_not(self, method, message=''):

TimeoutException: Message:

**Comment by Altimis** [comment]
Fixed
