### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by micaelamaria** [Altimis/Scweet#99]
Hi! I created a file called ".env" and saved it in the same folder I have my scraping code. When I run the command: 
following = get_users_following(users=users, env=env_path, verbose=0, headless=False, wait=2, limit=50, file_path=None) 
The excecution stops when the brower has to fill in the user and pass information. Any hints?

**Comment by Altimis** [comment]
Did you specify the location of the file in your code ? (example.py)

**Comment by micaelamaria** [comment]
Yes, I have: 
env_path = "/foldername/.env"

**Comment by Altimis** [comment]
Show me an example of what you put in the file (not your exact credentials tho)

**Comment by micaelamaria** [comment]
SCWEET_USERNAME=myusername
SCWEET_PASSWORD=mypass

**Comment by micaelamaria** [comment]
is it not right?

**Comment by micaelamaria** [comment]
Is anyone maintaining this repo?

**Comment by Altimis** [comment]
Sorry, I haven't had time to check the issue. I will get back to you this afternoon

**Comment by smicrasoft** [comment]
I think the script need to be updated, the login screen is not the same anymore. There is no "//input[@name="session[username_or_email]" anymore (cf utils.py)

**Comment by Altimis** [comment]
Yeah, I've just updated the code. I'll update the library soon

**Comment by Altimis** [comment]
@micaelamaria  @smicrasoft  can you confirm please so that I can close this issue

**Comment by micaelamaria** [comment]
@Altimis thanks - but then, what should we do to use get the following/followers? got confused now

**Comment by Altimis** [comment]
@micaelamaria  The same functions as before. See [Example.py](https://github.com/Altimis/Scweet/blob/master/Example.py) file

**Comment by Altimis** [comment]
@micaelamaria  But this time you need to specify the username and email of the account that u are using to scrape following/followers. (see .env)

**Comment by micaelamaria** [comment]
Just tried it and not working: 
"StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=96.0.4664.110)"

**Comment by Altimis** [comment]
@micaelamaria Did you install the latest version ? (1.8)

**Comment by micaelamaria** [comment]
yes

**Comment by Altimis** [comment]
Show me your code please. I already tested the new code and it works

**Comment by micaelamaria** [comment]
ok, now it works (restarted kernel), but the issue is another one: 
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/[useriamscraping]_[useriamscraping]_following.json'

**Comment by Altimis** [comment]
Yeah, maybe it has to do with the file containing following and followers being saved. You can take the output of the function (get_following and get_followers) and save it manually

**Comment by Altimis** [comment]
Do not specify the output file path in the function (show me the arguments of your function)

**Comment by micaelamaria** [comment]
following = get_users_following(users=users, env=env_path, verbose=0, headless=True, wait=2, limit=100)

**Comment by micaelamaria** [comment]
this error persists as well. StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: headless chrome=96.0.4664.110)

**Comment by Altimis** [comment]
Try setting <file_path> argument with None. I will update the repo later to fix this issue

**Comment by micaelamaria** [comment]
it doesn t work either :(

**Comment by Altimis** [comment]
@micaelamaria  increase <wait> argument (set it to 3 or 4) and test

**Comment by Altimis** [comment]
@micaelamaria  Regarding the No such file or directory: 'outputs/[useriamscraping]_[useriamscraping]_following.json' issue. You need to create a directory called outputs in the same location of your python file. I will update the code to create it automatically.

**Comment by micaelamaria** [comment]
I get now a new error: "NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@autocomplete="current-password"]"}
  (Session info: headless chrome=96.0.4664.110)"

**Comment by micaelamaria** [comment]
worked now ;)

**Comment by smicrasoft** [comment]
Seems working from "Example.py", ty !
